### ISSUE TITLE
Discussion views are on wrong side

### ISSUE THREAD

**Issue by SKevo18** [irmmr/flarum-ext-rtl#4]
Affected extension: 

Possible CSS fix:

```css
.item-discussion-views {
    float: left !important;
    margin-right: unset !important;
    margin-left: -65px;
}

.item-discussion-views .icon {
    margin-left: 5px !important;
    margin-right: unset !important;
}
```

Before:

<img width="865" alt="image" src="https://github.com/user-attachments/assets/efec2032-00dc-449e-926e-b4f12c72df60">

After:

<img width="858" alt="image" src="https://github.com/user-attachments/assets/6d0909f6-4f09-45e0-adaa-84bb59ba61e2">

Note: the mobile view still needs to be adjusted
